# Generated by Django 3.1.7 on 2021-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20210304_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
