# Generated by Django 3.1.7 on 2021-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20210309_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_personal_goal',
            field=models.BooleanField(default=False),
        ),
    ]
