# Generated by Django 3.1.7 on 2021-03-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_auto_20210310_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='is_reschedule',
            field=models.BooleanField(default=False),
        ),
    ]
