# Generated by Django 3.1.7 on 2021-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_subgoal_is_reschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_reschedule',
            field=models.BooleanField(default=False),
        ),
    ]
