# Generated by Django 3.1.7 on 2021-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_auto_20210325_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_personal_goal',
            field=models.BooleanField(default=False),
        ),
    ]
